version: '3.8'

services:
  mongo:
    image: mongo:6
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    restart: always
    networks:
      - app-network

  backend:
    build: ./backend
    ports:
      - "8080:5000"
    depends_on:
      - mongo
    environment:
      - MONGO_URI=mongodb://mongo:27017/wouldyourather
      - SECRET_KEY=${SECRET_KEY}
      - ANTHROPIC_API_KEY=${ANTHROPIC_API_KEY}
    networks:
      - app-network
    restart: always

  frontend:
    build: ./frontend
    ports:
      - "8000:80"
    depends_on:
      - backend
    networks:
      - app-network
    restart: always

networks:
  app-network:

volumes:
  mongo_data: