services:
  - type: web
    name: wouldyourather-backend
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn --config gunicorn_config.py wsgi:app
    envVars:
      - key: MONGO_URI
        sync: false
      - key: SECRET_KEY
        sync: false 
      - key: ANTHROPIC_API_KEY
        sync: false
    healthCheckPath: /